# 网络配置
network:
  environment: testnet  # 可选值：testnet/mainnet
  
  testnet:
    rpc_url: "https://fullnode.testnet.sui.io:443"
    private_key: "xxx"
  
  mainnet:
    rpc_url: "https://fullnode.mainnet.sui.io:443"
    private_key: "xxx"

strategies:
  AIStrategy:
    api_key: "xxx"
    endpoint: "xxx"
    model: "deepseek-v3-241226"
    priority: 100

# 智能合约配置
contracts:
  testnet: "0xTESTNET_CONTRACT_ADDRESS"
  mainnet: "0xMAINNET_CONTRACT_ADDRESS"

# 数据源配置
data:
  url: http://47.242.141.201:8091/priapi/v5/dex/token/market/dex-token-candles


# 程序设置
settings:
  interval_seconds: 3  # 执行间隔（秒）
  gas_budget: 10000000    # 交易gas预算